# Generated by Django 5.0.3 on 2024-03-26 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_list_app', '0002_shoppinglist_product_shopping_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglist',
            name='checked_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
