# Generated by Django 5.0.3 on 2024-03-29 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_list_app', '0003_shoppinglist_checked_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppinglist',
            name='add_date',
            field=models.DateTimeField(),
        ),
    ]
